spring:
  application:
    name: order-service

  datasource:
    url: ${ORDER_SERVICE_DATABASE_URL}
    username: ${ORDER_SERVICE_DATABASE_USERNAME}
    password: ${ORDER_SERVICE_DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

inventory:
  service:
    url: https://inventory-service-1dmr.onrender.com